        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='feedback_responsiveness',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='interaction_frequency',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='learning_style_preference',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='tech_proficiency',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='time_management_habits',
        ),
    ]
