# Generated by Django 3.2.25 on 2025-05-18 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecord',
            name='content_difficulty_perception',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='feedback_responsiveness',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='interaction_frequency',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='learning_style_preference',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='tech_proficiency',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='time_management_habits',
        ),
    ]
