# Generated by Django 3.2.25 on 2025-05-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_auto_20250518_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, help_text='学生的学号，可选但唯一', max_length=50, null=True, unique=True, verbose_name='学号'),
        ),
    ]
