# Generated by Django 3.2.25 on 2025-05-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_alter_userprofile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='unknown', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(help_text='用户的真实姓名或常用名', max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('admin', '管理员')], default='student', max_length=10, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, help_text='学生的学号。对于学生角色，系统通常会自动生成；对于其他角色，此字段可选。', max_length=50, null=True, unique=True, verbose_name='学号'),
        ),
    ]
